In [3]:
import numpy as np
import pandas as pd

In [2]:
!pip install numpy pandas scikit-learn matplotlib seaborn

Collecting numpy
  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting pandas
  Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\sales-intelligence-system\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp314-cp314-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (26.1)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in d:\sales-intelligence-system\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 1.7 MB/s eta 0:00:05
   ------- -------------------------------- 1.3/7.2 MB 2.7 MB/s eta 0:00:03
   -------------- ------------------------- 2.6/7.2 MB 3.9 MB/s eta 0:00:02
   -------------- ------------------------- 2.6/7.2 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 4.2/7.2 MB 3.8 MB/s eta 0:00:01
   --------------------------- ------------ 5.0/7.2 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 5.2/7.2 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 6.8/7.2 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 3.8 MB/s  0:00:02
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib, seaborn

   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----------------------------------------  0/15 [tzdata]
   ----- ----------------------------------  2/15 [pyparsing]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   -------- -------------------------------  3/15 [pillow]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------- -----------------------------  4/15 [numpy]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ---------------- -----------------------  6/15 [joblib]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------ ---------------------  7/15 [fonttools]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   ------------------------ ---------------  9/15 [scipy]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   ----------------------------- ---------- 11/15 [contourpy]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]
   -------------------------------- ------- 12/15 [scikit-learn]

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df=pd.read_csv('D:\\sales-intelligence-system\\data\\raw\\SampleSuperstore.csv')

In [7]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [ ]:
df.describe()# Check for missing values

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000