In [2]:
import numpy as np
import pandas as pd

In [3]:
!pip install numpy pandas scikit-learn matplotlib seaborn

Requirement already satisfied: numpy in d:\sales-intelligence-system\.venv\lib\site-packages (2.4.4)
Requirement already satisfied: pandas in d:\sales-intelligence-system\.venv\lib\site-packages (3.0.2)
Requirement already satisfied: scikit-learn in d:\sales-intelligence-system\.venv\lib\site-packages (1.8.0)
Requirement already satisfied: matplotlib in d:\sales-intelligence-system\.venv\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in d:\sales-intelligence-system\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\sales-intelligence-system\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\sales-intelligence-system\.venv\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.10.0 in d:\sales-intelligence-system\.venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in d:\sales-intelligence-system\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\sales-intelligence-system\.venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in d:\sales-intelligence-system\.venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in d:\sales-intelligence-system\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
df=pd.read_csv('D:\\sales-intelligence-system\\data\\raw\\SampleSuperstore.csv')

In [8]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [9]:
df.describe()# Check for missing values

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [10]:
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns